version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: crypto-alert-postgres
    environment:
      POSTGRES_DB: crypto_alerts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - crypto-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Node.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crypto-alert-app
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/crypto_alerts
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      PORT: 6000
    ports:
      - "6000:6000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - crypto-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  crypto-network:
    driver: bridge 